### ISSUE TITLE
QgsMapCanvas depends on overview canvas

### ISSUE THREAD

**Issue by wonder-sk** [qgis/qgis3.0_api#10]
There should not be such dependency. `QgsMapCanvas` does not need to know anything about overview canvas and any overview canvas just needs to follow changes of main canvas.

**Comment by nyalldawson** [comment]
@wonder-sk this was fixed by https://github.com/qgis/QGIS/commit/2c9f1ff579c79f99090869a247ad5a314cb261a3, right?

**Comment by wonder-sk** [comment]
Right!
