### ISSUE TITLE
Label rotation is in opposite direction to symbology

### ISSUE THREAD

**Issue by nyalldawson** [qgis/qgis3.0_api#18]
Label rotation is applied counter-clockwise, symbology rotation is clockwise. 

I'd like to alter the labelling behaviour so that rotation is applied clockwise to match symbol rotation. 

If we allow project breaks for 3.0, this should be an easy fix. If not, rotation would have to be upgraded with projects to 3.0 to reverse the label rotation angle.

**Comment by haubourg** [comment]
+1 for project break. Maybe we could provide a snippet for those that need to do mass upgrade?

**Comment by m-kuhn** [comment]
No problem with project breaks where inevitable. If it's not too hard, consider upgrading it in QgsProjectFileTransform::transform2990. Just write the new variable into an attribute with a different name and you know if it has already been trasnformed or not.

**Comment by nyalldawson** [comment]
Fixed in https://github.com/qgis/QGIS/commit/21a4ac4d3a747182c78224e23718bd09c6243d73
