### ISSUE TITLE
Rename QGis -> QGIS

### ISSUE THREAD

**Issue by nyalldawson** [qgis/qgis3.0_api#22]
Very minor thing, but the QGis class should be renamed to QGIS. It's an acronym after all ;)

**Comment by rduivenvoorde** [comment]
not really related, but just for a reference:
http://spatialgalaxy.net/2014/03/29/why-all-qgis-classes-start-with-qgs/
:-)

**Comment by nyalldawson** [comment]
Implemented in https://github.com/qgis/QGIS/commit/1a2231f10c65c2bef992e02046baebf3bc4975f6 (+ follow ups)
