### ISSUE TITLE
QgsMapLayerRegistry is a singleton

### ISSUE THREAD

**Issue by NathanW2** [qgis/qgis3.0_api#23]
It's handy but makes testing, and isolation hard.  Lots of code assumes that the layer is in the registry and uses IDs which requires extra looks into the registry e.g the map renderers

Going forward I think code that needs a layer should take `QgsMapLayer` objects and not use the ID. Remove any use of `QgsMapLayerRegistry` that isn't needed and link the active instance to `QgsProject`

```
project = QgsProject.open('blah.qgs')
project.layers()
```

**Comment by NathanW2** [comment]
Dup of #16

**Comment by NathanW2** [comment]
Leaving open as it's really a follow on from #16

**Comment by rldhont** [comment]
also discussed in #42

**Comment by nyalldawson** [comment]
Fixed in https://github.com/qgis/QGIS/commit/d56a97d4fe21f593746f176ceb6f553eca1d4c2e
