### ISSUE TITLE
Make QgsVectorDataProvider::Capability use QFlags

### ISSUE THREAD

**Issue by nyalldawson** [qgis/qgis3.0_api#24]
Instead of returning an int from QgsVectorDataProvider::capabilities(), it should instead return a Capabilities QFlags class for type safety/ease of use.

**Comment by m-kuhn** [comment]
Can we not already do that now with a separate method?

I would prefer renaming it to another name anyway, using the same name with a different semantics may result in strange results which are hard to debug, no?

**Comment by nyalldawson** [comment]
Wouldn't adding a separate method for this break 3rd party providers?

**Comment by m-kuhn** [comment]
Just realized that it wouldn't actually change the semantics.
Forget my comment.

**Comment by nyalldawson** [comment]
Implemented in https://github.com/qgis/QGIS/commit/58856fe82f14e1d3b500584116349a53f62e617d
