### ISSUE TITLE
eVis plugin and UTF8

### ISSUE THREAD

**Issue by snwl** [qgis/qgis3.0_api#27]
Hello,
I'm using plugin eVis on QGIS 2.12.1, os win 10. If I make database conections to MS Access or MS SQL and then import some data to QGIS I get a mesh. I use CP  win1250.  Character like "ŠČŽ" become "&$%" so I thing there is a problem with UTF8?  If is there use of function str() maybe unicode() will be better? Just guess.
Thanks

**Comment by wonder-sk** [comment]
This tracker is dedicated solely for future planning of API changes for QGIS 3.0. If you think you have found a bug in QGIS, then please report it in the QGIS bug tracker:
http://hub.qgis.org/projects/quantum-gis

**Comment by snwl** [comment]
OK. Sorry for my post - wrong sections.

**Comment by m-kuhn** [comment]
@nyalldawson I don't have admin rights in here. Can you close this?
