### ISSUE TITLE
Use C++11 in source code

### ISSUE THREAD

**Issue by wonder-sk** [qgis/qgis3.0_api#35]
All interesting features from c++11 have been introduced in compilers we use, so there is no reason not to switch to the newer standard and use the nice new stuff like:
* ```auto``` - type inference (e.g. great for iterators)
* lambda expressions
* new safer Qt connect syntax https://woboq.com/blog/cpp11-in-qt5.html
* ... and much more! :-)

**Comment by m-kuhn** [comment]
Proper link to [new style signals and slots](https://woboq.com/blog/new-signals-slots-syntax-in-qt5.html)

**Comment by nyalldawson** [comment]
Also worth noting that Qt >= 5.7 will be c++11 only (https://wiki.qt.io/New_Features_in_Qt_5.7)

**Comment by NathanW2** [comment]
I like that new signal and slot style.

**Comment by nyalldawson** [comment]
Done now, we've switched to c++11 only builds. I don't think we need to keep this task open and instead we can just implement bits of c++11 as required. It shouldn't affect api anyway.
