### ISSUE TITLE
Switch QList to QVector

### ISSUE THREAD

**Issue by nyalldawson** [qgis/qgis3.0_api#38]
many QGIS methods return QList<..>. For a lot of these cases we should be returning QVector<...>
(see https://marcmutz.wordpress.com/effective-qt/containers/)

**Comment by m-kuhn** [comment]
or QSet...

**Comment by nyalldawson** [comment]
Closing this. Given that it doesn't affect the python api, we can flip methods across at anytime

**Comment by m-kuhn** [comment]
yahoo 🥇
