### ISSUE TITLE
Kill off QgsLabel

### ISSUE THREAD

**Issue by NathanW2** [qgis/qgis3.0_api#39]
`QgsLabel` is a old label class.  Kill it in 3.0 or rename the new labeling into this class?

**Comment by wonder-sk** [comment]
I would say just kill it, with no renaming. There are several labeling classes after labeling refactoring now, so it's not clear which one should become ```QgsLabel```

**Comment by NathanW2** [comment]
+1 on death to `QgsLabel`

**Comment by wonder-sk** [comment]
Aaaand it's gone (qgis/QGIS@31c75ef22ec944a722f1c5f188bbc39a976bd8cd)
