### ISSUE TITLE
GDAL 2

### ISSUE THREAD

**Issue by wonder-sk** [qgis/qgis3.0_api#41]
It may be sensible to migrate QGIS 3 code to use GDAL 2 so we can remove any legacy code using GDAL 1.x APIs and make assumptions that new features from 2.0 are always present.

**Comment by nyalldawson** [comment]
So have a hard dependency on GDAL > 2.0? I'd love this, but have my doubts that all our target platforms will have this dependency ready by the time we release 3.0.

Eg, looks like Ubuntu 16.04 LTS has unfortunately missed the cut: 
https://lists.osgeo.org/pipermail/gdal-dev/2016-March/043906.html

**Comment by pcav** [comment]
IMHO we can safely move. The Ubuntu situation can be fixed with backports.

**Comment by 3nids** [comment]
done in https://github.com/qgis/QGIS/commit/b0bc763
