### ISSUE TITLE
Remove old snapping classes

### ISSUE THREAD

**Issue by 3nids** [qgis/qgis3.0_api#44]
I think we should remove old snapping classes which are very inefficient QgsSnapper, QgsSnappingResult, QgsMapCanvasSnapper).
What do you think?

**Comment by nyalldawson** [comment]
It's a +1 from me...

**Comment by nyalldawson** [comment]
@wonder-sk this can be closed now, right?

**Comment by wonder-sk** [comment]
Yeah - done!
