### ISSUE TITLE
Rewrite in GTK

### ISSUE THREAD

**Issue by nyalldawson** [qgis/qgis3.0_api#50]

**Comment by nyalldawson** [comment]
assigned to @m-kuhn

**Comment by m-kuhn** [comment]
Do we need a new major version number for a simple patch like this?

**Comment by nyalldawson** [comment]
Nope. Can you backport to 2.14 too?

**Comment by m-kuhn** [comment]
I'd say we just do it as a plugin so it can even be used with 1.8

**Comment by wonder-sk** [comment]
Any reason not to use tcl/tk instead?

**Comment by m-kuhn** [comment]
does that run on openmoko?

**Comment by wonder-sk** [comment]
I dont know, I am only concerned about smooth UX on my EPOC based Psion device.

**Comment by m-kuhn** [comment]
How about [curses](https://github.com/NathanW2/ascii_qgis)?

**Comment by jef-n** [comment]
I use curses all the time on windows.

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/commit/65124e
