### ISSUE TITLE
Remove (or update) QgsGeometryAnalyzer and QgsOverlayAnalyser

### ISSUE THREAD

**Issue by alexbruy** [qgis/qgis3.0_api#60]
[QgsOverlayAnalyzer](https://github.com/qgis/QGIS/blob/master/src/analysis/vector/qgsoverlayanalyzer.h) and [QgsGeometryAnalyser](https://github.com/qgis/QGIS/blob/master/src/analysis/vector/qgsgeometryanalyzer.h) classes were added as attempt to port fTools plugin to C++. But they were not used in fTools or any other part of QGIS.

It would be nice to review them and make more generic, so they can be used in Processing and other plugins. Or if this makes no sense — just remove them.

**Comment by nyalldawson** [comment]
My vote goes to removing them once the processing framework is accessible through c++.

**Comment by nyalldawson** [comment]
Fixed - these classes were removed
