### ISSUE TITLE
Remove QgsColorButton in favor of V2

### ISSUE THREAD

**Issue by 3nids** [qgis/qgis3.0_api#61]
Shall we remove QgsColorButton and use only v2 (renamed as QgsColorButton)?

**Comment by nyalldawson** [comment]
Yes, there's no good reason to keep it around

**Comment by jef-n** [comment]
Yes, add fuel to the burning bridges :)

**Comment by 3nids** [comment]
fixed in 3e197ae74a91f607cd9eb159cd4e07fd44e7e85e

**Comment by 3nids** [comment]
on which shore are you ? ;)

![image](https://cloud.githubusercontent.com/assets/127259/17401782/c9b452de-5a4f-11e6-9162-1ecb857cbfa9.png)
