### ISSUE TITLE
Rename QgsGeometry::isEmpty()

### ISSUE THREAD

**Issue by wonder-sk** [qgis/qgis3.0_api#72]
A better name for the method would be isNull()... as it checks whether QgsGeometry contains "nothing". This would avoid confusion with isGeosEmpty() which acts like ST_IsEmpty() from PostGIS and returns true for cases like empty geometry collection.

**Comment by nyalldawson** [comment]
True. Additionally - we shouldn't really require isGeosEmpty(), as it would be trivial to add a proper isEmpty() method which uses the qgis geometry classes and doesn't require the geos conversion.

**Comment by nyalldawson** [comment]
Fixed in https://github.com/qgis/QGIS/commit/8709e1f9d5e1ba4fa2c5b2a6bdc19e1248c4c3f5
