### ISSUE TITLE
When should features be made valid?

### ISSUE THREAD

**Issue by nyalldawson** [qgis/qgis3.0_api#75]
Copying some discussion from https://github.com/qgis/QGIS/pull/4147:

>>  @m-kuhn Should there also be a removeFeature() method or setFeature() check for feature validity?
> @nyalldawson I also tried initially using the feature validity check instead of the separate bool member, but the issue here is that the valid flag cannot be relied on alone as a indication of whether a feature has been set or not. E.g. I had test failures after making that change. I think the issue stems from QgsFeature defaulting to isValid false, so code like:

    f = QgsFeature()
    f.setGeometry( ... )
    f.setAttributes(. ...)
    scope.setFeature( f )

> @nyalldawson Would incorrectly ignore the feature because it's still flagged as not valid. There's still many parts of the code which create features without setting the validity flag (fortunately provider created features are safe here).

> @m-kuhn  Could we set the feature to valid as soon as setGeometry() or setAttributes() is called?

So this is to discuss the QgsFeature::isValid flag and when it should be set...

**Comment by m-kuhn** [comment]
Thanks for raising this, I think it would make API usage easier and eliminate a common pitfall.

The following snippet demonstrates what I think would be a natural way of dealing with feature validity:

```py
f = QgsFeature()
f.isValid()
> False
f.setGeometry( ... )
f.isValid()
> True
f.setValid(False)
f.setAttributes(. ...)
f.isValid()
> True
f.setValid(False)
f.isValid()
> False
```

CC @wonder-sk @NathanW2 @jef-n @mhugent @elpaso @mhugo 

Any objections?
