### ISSUE TITLE
Rename all qgs*.h and qgs*.cpp files to introduce and underscore between "qgs" prefix and class name

### ISSUE THREAD

**Issue by elpaso** [qgis/qgis3.0_api#77]
Not really an API change, and maybe it's just me, but I find difficult to read the file listing, such as:

```
qgsindexedfeature.h
qgsinterval.cpp
qgsinterval.h
qgsjsonutils.cpp
qgsjsonutils.h
qgslabelattributes.cpp
qgslabelattributes.h
qgslabel.cpp
qgslabelfeature.cpp
qgslabelfeature.h
qgslabel.h
```

I'd like to rename the files to:

```
qgs_indexedfeature.h
qgs_interval.cpp
qgs_interval.h
qgs_jsonutils.cpp
qgs_jsonutils.h
qgs_labelattributes.cpp
qgs_labelattributes.h
qgs_label.cpp
qgs_labelfeature.cpp
qgs_labelfeature.h
qgs_label.h
```

The disadvantage is that there will be no more matching between class names and (lowercase) file names.

Crazy idea?

**Comment by strk** [comment]
How about having the filename be MixedCast to exactly match class name ?
I'd love it :)

**Comment by elpaso** [comment]
@strk that would also help my myopia :)


```
QgsIndexedFeature.h
QgsInterval.cpp
QgsInterval.h
QgsJsonUtils.cpp
QgsJsonUtils.h
QgsLabelAttributes.cpp
QgsLabelAttributes.h
QgsLabel.cpp
QgsLabelFeature.cpp
QgsLabelFeature.h
QgsLabel.h
```

yeah, that looks good!

**Comment by 3nids** [comment]
As pointed in the other renaming issue, you'll lose git history due to the renaming too.

**Comment by NathanW2** [comment]
Not sure you loose any history.  Git is smarter then that if you don't
change the content of the file.

**Comment by 3nids** [comment]
Sorry not git history just the history link on github, it doesn't follow
renaming.

Le ven. 17 mars 2017 à 11:20, Nathan Woodrow <notifications@github.com> a
écrit :

**Comment by strk** [comment]
That's a GitHub limitation/bug.
Git is smarter than GitHub.

File a ticket to GitHub source code ? Oh, oops, GitHub is not open source.
What about moving QGIS source code in a better place ?
GitLab might not be too bad as a move ...

**Comment by 3nids** [comment]
I'm OK to move to gitlab but please keep the issue tracker on Redmine.

**Comment by NathanW2** [comment]
Can we stay focued on the ticket here and what it addresses instead of
other lets move git hosts.

I'm happy to talk about it but one thing at a time given we already have
enough on at the moment.

**Comment by strk** [comment]
So personally I think git history is best checked locally
than via a web browser (so you can grep, for example).
Name changes are followed by `git log --follow <filename>`

**Comment by m-kuhn** [comment]
While it's probably nicer to read, I fear that it will end up in more typing. I tend to write the filenames a lot in the terminal and IDE and includes. `_` is one of the harder characters to type (Alt + key bottom right on my keyboard). `CamelCase` would be acceptable. But actually I quite got use to the way it is and see no big reason to change :-)

**Comment by elpaso** [comment]
@m-kuhn yes, that's not a revolutionary change and there is no *big* reason, it's just a *small* improvement with readability of file listings. I just thought that this might be the right moment to do that.

**Comment by strk** [comment]
@m-kuhn does your shell not support TAB-completion ? :)

**Comment by elpaso** [comment]
BTW, I think that the camel case is actually a better solution than the underscore, the file name would match the name of the class, which is good.

**Comment by NathanW2** [comment]
Not a fan of camel case for files, makes it annoying to type.

**Comment by strk** [comment]
Agreed about CamelCase being better than underscores

**Comment by m-kuhn** [comment]
It's typing

    <shift><Q> -> <tab> -> <shift> <some-otherletter>

vs. currently

    <q> -> <tab> -> <some-otherletter>

That's with tab-completion.

**Comment by jef-n** [comment]
Potential pain w/o much gain.

**Comment by timlinux** [comment]
@elpaso I'm also of the opinion that if we make such a sweeping change that will potentially affect so many developers, scripts etc. that may be out there, we should have a good rationale for making the change.  There was a similar discussion about removing the Qgs prefix for classes in favour of using namespaces. If we do remove the Qgs prefix, this ticket would be redundant, and if we don't, we may as well stick with the scheme that folks are already familiar with.
