### ISSUE TITLE
Fix inconsistency by renaming QgsGeometry exportToWkt/geoJSON to as*

### ISSUE THREAD

**Issue by elpaso** [qgis/qgis3.0_api#81]
We currently have:
- exportToWkt
- exportToJson
- asWkb

I suggest to change the first two to `asWkt` and `asGeoJson`, but renaming `asWkb` is also an option.

**Comment by m-kuhn** [comment]
+1, `asWkt` sounds good to me

**Comment by luipir** [comment]
+1

**Comment by wonder-sk** [comment]
Hasn't this been addressed some time ago? :-)

https://github.com/qgis/QGIS/blob/master/src/core/geometry/qgsgeometry.h#L879

**Comment by elpaso** [comment]
Oh, sorry for the noise
